name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Install fleet
        run: cargo install cargo-fleet

      - name: Install sccache
        run: cargo install sccache

      - name: Run tests
        run: cargo test --verbose
